name: action_tester

on: [push]

jobs:
  custom_test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Get Pokemon name
        # uses: philschmid/blog-custom-github-action@master
        uses: ./ # Uses an action in the root directory
        id: pokemon
        with:
          pokemon_id: 150
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
